IQDate\UserBundle\Entity\IQUser:
    type: entity
    repositoryClass: IQDate\UserBundle\Repository\IQUserRepository
    table: iq_user
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
          type: string
          length: 100
        nickname:
          type: string
          length: 100
        surname:
          type: string
          length: 100
        password:
          type: string
          length: 255
