services:
  user.services.user_service:
      class: IQDate\UserBundle\Services\UserService
      arguments: [ "@iqdate.user" ]
  iqdate.user:
          class: IQDate\UserBundle\Repository\IQUserRepositoryInterface
          factory: ["@doctrine.orm.entity_manager", getRepository]
          arguments:
              - UserBundle:IQUser
  iqdate_user.security_user.user_provider:
      class: IQDate\UserBundle\Security\User\UserProvider
      arguments: ['@iqdate.user']